version: "3"
services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - data01:/usr/share/elasticsearch/data
  kibana:
    #image: docker.elastic.co/kibana/kibana:7.11.2
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana01
    ports:
      - 5601:5601
volumes:
  data01:
    driver: local
